[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "/admin.html"
  [headers.values]
    X-Robots-Tag = "noindex"
[[headers]]
  for = "/cancel.html"
  [headers.values]
    X-Robots-Tag = "noindex"
